apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: self-healing-microservice
  template:
    metadata:
      labels:
        app: self-healing-microservice
    spec:
      containers:
      - name: self-healing-microservice
        image: nishit7908/node-docker:03
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: self-healing-microservice
spec:
  selector:
    app: self-healing-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
